using System.ComponentModel.DataAnnotations;
using RHPortal.Api.Domain.Enums;

namespace RhPortal.Api.Contracts.Vagas;

public sealed record VagaCreateRequest(
    [Required, MaxLength(160)] string Titulo,
    [Required] Guid DepartmentId,
    [Required] Guid AreaId,
    [Required] VagaStatus Status,
    [MaxLength(40)] string? Codigo,
    VagaAreaTime? AreaTime,
    VagaModalidade? Modalidade,
    VagaSenioridade? Senioridade,
    int QuantidadeVagas,
    VagaTipoContratacao? TipoContratacao,
    int MatchMinimoPercentual,
    VagaWeightsRequest? Weights,
    string? DescricaoInterna,
    [MaxLength(40)] string? CodigoInterno,
    [MaxLength(20)] string? CodigoCbo,
    VagaMotivoAbertura? MotivoAbertura,
    VagaOrcamentoAprovado? OrcamentoAprovado,
    [MaxLength(120)] string? GestorRequisitante,
    [MaxLength(120)] string? RecrutadorResponsavel,
    VagaPrioridade? Prioridade,
    string? ResumoPitch,
    string? TagsResponsabilidadesRaw,
    string? TagsKeywordsRaw,
    bool Confidencial,
    bool AceitaPcd,
    bool Urgente,
    VagaGeneroPreferencia? GeneroPreferencia,
    bool VagaAfirmativa,
    bool LinguagemInclusiva,
    [MaxLength(120)] string? PublicoAfirmativo,
    string? ObservacoesPcd,
    [MaxLength(160)] string? ProjetoNome,
    [MaxLength(160)] string? ProjetoClienteAreaImpactada,
    [MaxLength(80)] string? ProjetoPrazoPrevisto,
    string? ProjetoDescricao,
    VagaRegimeJornada? Regime,
    int? CargaSemanalHoras,
    VagaEscalaTrabalho? Escala,
    TimeOnly? HoraEntrada,
    TimeOnly? HoraSaida,
    TimeSpan? Intervalo,
    [MaxLength(12)] string? Cep,
    [MaxLength(160)] string? Logradouro,
    [MaxLength(20)] string? Numero,
    [MaxLength(120)] string? Bairro,
    [MaxLength(120)] string? Cidade,
    [MaxLength(2)] string? Uf,
    [MaxLength(200)] string? PoliticaTrabalho,
    [MaxLength(200)] string? ObservacoesDeslocamento,
    VagaMoeda? Moeda,
    decimal? SalarioMinimo,
    decimal? SalarioMaximo,
    VagaRemuneracaoPeriodicidade? Periodicidade,
    VagaBonusTipo? BonusTipo,
    decimal? BonusPercentual,
    [MaxLength(240)] string? ObservacoesRemuneracao,
    VagaEscolaridade? Escolaridade,
    VagaFormacaoArea? FormacaoArea,
    int? ExperienciaMinimaAnos,
    string? TagsStackRaw,
    string? TagsIdiomasRaw,
    string? Diferenciais,
    string? ObservacoesProcesso,
    VagaPublicacaoVisibilidade? Visibilidade,
    DateOnly? DataInicio,
    DateOnly? DataEncerramento,
    bool CanalLinkedIn,
    bool CanalSiteCarreiras,
    bool CanalIndicacao,
    bool CanalPortaisEmprego,
    string? DescricaoPublica,
    bool LgpdSolicitarConsentimentoExplicito,
    bool LgpdCompartilharCurriculoInternamente,
    bool LgpdRetencaoAtiva,
    int? LgpdRetencaoMeses,
    bool ExigeCnh,
    bool DisponibilidadeParaViagens,
    bool ChecagemAntecedentes,
    IReadOnlyList<VagaBeneficioRequest>? Beneficios,
    IReadOnlyList<VagaRequisitoRequest>? Requisitos,
    IReadOnlyList<VagaEtapaRequest>? Etapas,
    IReadOnlyList<VagaPerguntaRequest>? PerguntasTriagem
);

public sealed record VagaUpdateRequest(
    [Required, MaxLength(160)] string Titulo,
    [Required] Guid DepartmentId,
    [Required] Guid AreaId,
    [Required] VagaStatus Status,
    [MaxLength(40)] string? Codigo,
    VagaAreaTime? AreaTime,
    VagaModalidade? Modalidade,
    VagaSenioridade? Senioridade,
    int QuantidadeVagas,
    VagaTipoContratacao? TipoContratacao,
    int MatchMinimoPercentual,
    VagaWeightsRequest? Weights,
    string? DescricaoInterna,
    [MaxLength(40)] string? CodigoInterno,
    [MaxLength(20)] string? CodigoCbo,
    VagaMotivoAbertura? MotivoAbertura,
    VagaOrcamentoAprovado? OrcamentoAprovado,
    [MaxLength(120)] string? GestorRequisitante,
    [MaxLength(120)] string? RecrutadorResponsavel,
    VagaPrioridade? Prioridade,
    string? ResumoPitch,
    string? TagsResponsabilidadesRaw,
    string? TagsKeywordsRaw,
    bool Confidencial,
    bool AceitaPcd,
    bool Urgente,
    VagaGeneroPreferencia? GeneroPreferencia,
    bool VagaAfirmativa,
    bool LinguagemInclusiva,
    [MaxLength(120)] string? PublicoAfirmativo,
    string? ObservacoesPcd,
    [MaxLength(160)] string? ProjetoNome,
    [MaxLength(160)] string? ProjetoClienteAreaImpactada,
    [MaxLength(80)] string? ProjetoPrazoPrevisto,
    string? ProjetoDescricao,
    VagaRegimeJornada? Regime,
    int? CargaSemanalHoras,
    VagaEscalaTrabalho? Escala,
    TimeOnly? HoraEntrada,
    TimeOnly? HoraSaida,
    TimeSpan? Intervalo,
    [MaxLength(12)] string? Cep,
    [MaxLength(160)] string? Logradouro,
    [MaxLength(20)] string? Numero,
    [MaxLength(120)] string? Bairro,
    [MaxLength(120)] string? Cidade,
    [MaxLength(2)] string? Uf,
    [MaxLength(200)] string? PoliticaTrabalho,
    [MaxLength(200)] string? ObservacoesDeslocamento,
    VagaMoeda? Moeda,
    decimal? SalarioMinimo,
    decimal? SalarioMaximo,
    VagaRemuneracaoPeriodicidade? Periodicidade,
    VagaBonusTipo? BonusTipo,
    decimal? BonusPercentual,
    [MaxLength(240)] string? ObservacoesRemuneracao,
    VagaEscolaridade? Escolaridade,
    VagaFormacaoArea? FormacaoArea,
    int? ExperienciaMinimaAnos,
    string? TagsStackRaw,
    string? TagsIdiomasRaw,
    string? Diferenciais,
    string? ObservacoesProcesso,
    VagaPublicacaoVisibilidade? Visibilidade,
    DateOnly? DataInicio,
    DateOnly? DataEncerramento,
    bool CanalLinkedIn,
    bool CanalSiteCarreiras,
    bool CanalIndicacao,
    bool CanalPortaisEmprego,
    string? DescricaoPublica,
    bool LgpdSolicitarConsentimentoExplicito,
    bool LgpdCompartilharCurriculoInternamente,
    bool LgpdRetencaoAtiva,
    int? LgpdRetencaoMeses,
    bool ExigeCnh,
    bool DisponibilidadeParaViagens,
    bool ChecagemAntecedentes,
    IReadOnlyList<VagaBeneficioRequest>? Beneficios,
    IReadOnlyList<VagaRequisitoRequest>? Requisitos,
    IReadOnlyList<VagaEtapaRequest>? Etapas,
    IReadOnlyList<VagaPerguntaRequest>? PerguntasTriagem
);

public sealed record VagaResponse(
    Guid Id,
    string? Codigo,
    string Titulo,
    Guid DepartmentId,
    string? DepartmentCode,
    string? DepartmentName,
    VagaAreaTime? AreaTime,
    Guid AreaId,
    string? AreaCode,
    string? AreaName,
    VagaModalidade? Modalidade,
    VagaStatus Status,
    VagaSenioridade? Senioridade,
    int QuantidadeVagas,
    VagaTipoContratacao? TipoContratacao,
    int MatchMinimoPercentual,
    VagaWeightsResponse Weights,
    string? DescricaoInterna,
    string? CodigoInterno,
    string? CodigoCbo,
    VagaMotivoAbertura? MotivoAbertura,
    VagaOrcamentoAprovado? OrcamentoAprovado,
    string? GestorRequisitante,
    string? RecrutadorResponsavel,
    VagaPrioridade? Prioridade,
    string? ResumoPitch,
    string? TagsResponsabilidadesRaw,
    string? TagsKeywordsRaw,
    bool Confidencial,
    bool AceitaPcd,
    bool Urgente,
    VagaGeneroPreferencia? GeneroPreferencia,
    bool VagaAfirmativa,
    bool LinguagemInclusiva,
    string? PublicoAfirmativo,
    string? ObservacoesPcd,
    string? ProjetoNome,
    string? ProjetoClienteAreaImpactada,
    string? ProjetoPrazoPrevisto,
    string? ProjetoDescricao,
    VagaRegimeJornada? Regime,
    int? CargaSemanalHoras,
    VagaEscalaTrabalho? Escala,
    TimeOnly? HoraEntrada,
    TimeOnly? HoraSaida,
    TimeSpan? Intervalo,
    string? Cep,
    string? Logradouro,
    string? Numero,
    string? Bairro,
    string? Cidade,
    string? Uf,
    string? PoliticaTrabalho,
    string? ObservacoesDeslocamento,
    VagaMoeda? Moeda,
    decimal? SalarioMinimo,
    decimal? SalarioMaximo,
    VagaRemuneracaoPeriodicidade? Periodicidade,
    VagaBonusTipo? BonusTipo,
    decimal? BonusPercentual,
    string? ObservacoesRemuneracao,
    VagaEscolaridade? Escolaridade,
    VagaFormacaoArea? FormacaoArea,
    int? ExperienciaMinimaAnos,
    string? TagsStackRaw,
    string? TagsIdiomasRaw,
    string? Diferenciais,
    string? ObservacoesProcesso,
    VagaPublicacaoVisibilidade? Visibilidade,
    DateOnly? DataInicio,
    DateOnly? DataEncerramento,
    bool CanalLinkedIn,
    bool CanalSiteCarreiras,
    bool CanalIndicacao,
    bool CanalPortaisEmprego,
    string? DescricaoPublica,
    bool LgpdSolicitarConsentimentoExplicito,
    bool LgpdCompartilharCurriculoInternamente,
    bool LgpdRetencaoAtiva,
    int? LgpdRetencaoMeses,
    bool ExigeCnh,
    bool DisponibilidadeParaViagens,
    bool ChecagemAntecedentes,
    IReadOnlyList<VagaBeneficioResponse> Beneficios,
    IReadOnlyList<VagaRequisitoResponse> Requisitos,
    IReadOnlyList<VagaEtapaResponse> Etapas,
    IReadOnlyList<VagaPerguntaResponse> PerguntasTriagem,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);

public sealed record VagaBeneficioRequest(
    int Ordem,
    VagaBeneficioTipo Tipo,
    decimal? Valor,
    VagaBeneficioRecorrencia Recorrencia,
    bool Obrigatorio,
    string? Observacoes
);

public sealed record VagaRequisitoRequest(
    int Ordem,
    [MaxLength(80)] string? Categoria,
    [Required, MaxLength(180)] string Nome,
    VagaPeso Peso,
    bool Obrigatorio,
    int? AnosMinimos,
    VagaRequisitoNivel? Nivel,
    VagaRequisitoAvaliacao? Avaliacao,
    IReadOnlyList<string>? Sinonimos,
    [MaxLength(240)] string? Observacoes
);

public sealed record VagaEtapaRequest(
    int Ordem,
    [Required, MaxLength(160)] string Nome,
    VagaEtapaResponsavel Responsavel,
    VagaEtapaModo Modo,
    int? SlaDias,
    [MaxLength(240)] string? DescricaoInstrucoes
);

public sealed record VagaPerguntaRequest(
    int Ordem,
    [Required, MaxLength(220)] string Texto,
    VagaPerguntaTipo Tipo,
    VagaPeso Peso,
    bool Obrigatoria,
    bool Knockout,
    string? OpcoesRaw
);

public sealed record VagaBeneficioResponse(
    Guid Id,
    int Ordem,
    VagaBeneficioTipo Tipo,
    decimal? Valor,
    VagaBeneficioRecorrencia Recorrencia,
    bool Obrigatorio,
    string? Observacoes,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);

public sealed record VagaRequisitoResponse(
    Guid Id,
    int Ordem,
    string? Categoria,
    string Nome,
    VagaPeso Peso,
    bool Obrigatorio,
    int? AnosMinimos,
    VagaRequisitoNivel? Nivel,
    VagaRequisitoAvaliacao? Avaliacao,
    IReadOnlyList<string> Sinonimos,
    string? Observacoes,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);

public sealed record VagaWeightsRequest(
    int Competencia,
    int Experiencia,
    int Formacao,
    int Localidade
);

public sealed record VagaWeightsResponse(
    int Competencia,
    int Experiencia,
    int Formacao,
    int Localidade
);

public sealed record VagaEtapaResponse(
    Guid Id,
    int Ordem,
    string Nome,
    VagaEtapaResponsavel Responsavel,
    VagaEtapaModo Modo,
    int? SlaDias,
    string? DescricaoInstrucoes,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);

public sealed record VagaPerguntaResponse(
    Guid Id,
    int Ordem,
    string Texto,
    VagaPerguntaTipo Tipo,
    VagaPeso Peso,
    bool Obrigatoria,
    bool Knockout,
    string? OpcoesRaw,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc
);
