// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RhPortal.Api.Infrastructure.Data;

#nullable disable

namespace RHPortal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101155544_AddVagasTables")]
    partial class AddVagasTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.Vaga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AceitaPcd")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Area")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("AreaTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BonusPercentual")
                        .HasColumnType("TEXT");

                    b.Property<short?>("BonusTipo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanalIndicacao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanalLinkedIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanalPortaisEmprego")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanalSiteCarreiras")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CargaSemanalHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ChecagemAntecedentes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoCbo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confidencial")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataEncerramento")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<short>("Departamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoInterna")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoPublica")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diferenciais")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisponibilidadeParaViagens")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Escala")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Escolaridade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExigeCnh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExperienciaMinimaAnos")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("FormacaoArea")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("GeneroPreferencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GestorRequisitante")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("HoraEntrada")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("HoraSaida")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Intervalo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LgpdCompartilharCurriculoInternamente")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LgpdRetencaoAtiva")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LgpdRetencaoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LgpdSolicitarConsentimentoExplicito")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinguagemInclusiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchMinimoPercentual")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Modalidade")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Moeda")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("MotivoAbertura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesDeslocamento")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesPcd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesProcesso")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesRemuneracao")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<short?>("OrcamentoAprovado")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Periodicidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoliticaTrabalho")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<short?>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjetoClienteAreaImpactada")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjetoDescricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjetoNome")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjetoPrazoPrevisto")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicoAfirmativo")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeVagas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecrutadorResponsavel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<short?>("Regime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumoPitch")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalarioMaximo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalarioMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<short?>("Senioridade")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsIdiomasRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsKeywordsRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsResponsabilidadesRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsStackRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<short?>("TipoContratacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Urgente")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VagaAfirmativa")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Visibilidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Area");

                    b.HasIndex("TenantId", "Departamento");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Vagas", (string)null);
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.VagaBeneficio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Recorrencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<short>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VagaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VagaId");

                    b.HasIndex("TenantId", "VagaId");

                    b.ToTable("VagaBeneficios", (string)null);
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.VagaEtapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoInstrucoes")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<short>("Modo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Responsavel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SlaDias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VagaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VagaId");

                    b.HasIndex("TenantId", "VagaId");

                    b.ToTable("VagaEtapas", (string)null);
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.VagaPergunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Knockout")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Obrigatoria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpcoesRaw")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Peso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<short>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VagaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VagaId");

                    b.HasIndex("TenantId", "VagaId");

                    b.ToTable("VagaPerguntas", (string)null);
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.VagaRequisito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AnosMinimos")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Avaliacao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<short?>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Peso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VagaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VagaId");

                    b.HasIndex("TenantId", "VagaId");

                    b.ToTable("VagaRequisitos", (string)null);
                });

            modelBuilder.Entity("RhPortal.Api.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("RhPortal.Api.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchOrLocation")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Headcount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerEmail")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("RhPortal.Api.Domain.Entities.JobPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seniority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("JobPositions", (string)null);
                });

            modelBuilder.Entity("RhPortal.Api.Domain.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("Headcount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobPositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("UnitId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Managers", (string)null);
                });

            modelBuilder.Entity("RhPortal.Api.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("Headcount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibleName")
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.VagaBeneficio", b =>
                {
                    b.HasOne("RHPortal.Api.Domain.Entities.Vaga", "Vaga")
                        .WithMany("Beneficios")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.VagaEtapa", b =>
                {
                    b.HasOne("RHPortal.Api.Domain.Entities.Vaga", "Vaga")
                        .WithMany("Etapas")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.VagaPergunta", b =>
                {
                    b.HasOne("RHPortal.Api.Domain.Entities.Vaga", "Vaga")
                        .WithMany("PerguntasTriagem")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.VagaRequisito", b =>
                {
                    b.HasOne("RHPortal.Api.Domain.Entities.Vaga", "Vaga")
                        .WithMany("Requisitos")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("RhPortal.Api.Domain.Entities.Department", b =>
                {
                    b.HasOne("RhPortal.Api.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RhPortal.Api.Domain.Entities.JobPosition", b =>
                {
                    b.HasOne("RhPortal.Api.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RhPortal.Api.Domain.Entities.Manager", b =>
                {
                    b.HasOne("RhPortal.Api.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhPortal.Api.Domain.Entities.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhPortal.Api.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("JobPosition");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("RHPortal.Api.Domain.Entities.Vaga", b =>
                {
                    b.Navigation("Beneficios");

                    b.Navigation("Etapas");

                    b.Navigation("PerguntasTriagem");

                    b.Navigation("Requisitos");
                });
#pragma warning restore 612, 618
        }
    }
}
